name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # メインブランチへのプッシュ時に実行

permissions:
  pages: write  # GitHub Pagesへの書き込み権限
  id-token: write  # OIDCトークンの権限（`deploy-pages`用）

env:
  CARGO_TOOLS: shiroa

jobs:
  build:
    runs-on: ubuntu-slim

    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v4

      - name: 必要なツールのインストール
        # apt updateは必須： https://docs.github.com/ja/actions/using-github-hosted-runners/using-github-hosted-runners/customizing-github-hosted-runners#:~:text=%E5%B8%B8%E3%81%AB%E5%AE%9F%E8%A1%8C%E3%81%97%E3%81%A6%E3%81%8F%E3%81%A0%E3%81%95%E3%81%84
        run: |
          sudo apt update
          sudo apt install -y fonts-noto-cjk

      # 実際に使われるRustのバージョンを取得して、後のステップで使えるようにする
      - name: Rustのバージョンを取得
        id: rustc-version
        run: echo "version=$(rustc --version)" >> $GITHUB_OUTPUT

      # キャッシュキーに実際のRustバージョンを含める
      - name: Rust用のキャッシュ準備
        id: cache-cargo-install # if 条件で使うために id を設定
        uses: actions/cache@v4
        with:
          path: ~/.cargo/
          key: ${{ runner.os }}-cargo-install-${{ steps.rustc-version.outputs.version }}-${{ hashFiles('**/Cargo.lock') }}-${{ env.CARGO_TOOLS }}

      - name: キャッシュがヒットしなかった場合にのみツールをインストール
        if: steps.cache-cargo-install.outputs.cache-hit != 'true'
        run: cargo install --git https://github.com/Myriad-Dreamin/shiroa --locked shiroa

      - name: book.typ ファイルの検索と処理
        run: |
          find . -name book.typ -execdir bash -c '
            set -eux
            parent_dir=$(basename $(pwd))
            shiroa build --allowed-url-source ".*" --path-to-root "/$parent_dir/" --mode static-html;
            rm -rf "../public/$parent_dir";
            mkdir -p "../public/$parent_dir";
            mv dist/* "../public/$parent_dir/";
          ' bash {} \;

      - name: Pythonのセットアップ
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      # キャッシュが確実に効くようにバージョンを指定してある
      - run: pip install -r requirements.txt

      - name: トップページ生成
        run: python3 generator.py

      - name: upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
            path: ./public
    
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
